CREATE TABLE Library (
    ID SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    genre VARCHAR(100),
    date DATE NOT NULL,
    ISBN VARCHAR(100) NOT NULL UNIQUE
);
